### ISSUE TITLE
`eq`/`neq`: TS2367 "no overlap" errors silently dropped since 1.8.6 (regression via #1179)

### ISSUE THREAD

**Issue by NullVoxPopuli** [typed-ember/glint#1193]
# `eq`/`neq`: TS2367 "no overlap" errors silently dropped since 1.8.6 (regression via #1179)

## Summary

Since `@glint/ember-tsc` 1.8.6, a `(eq x "literal")` comparison where the literal has no overlap with `x`'s type no longer reports TS2367. The error is still produced by TypeScript in the transformed module — it's dropped during diagnostic mapping back to the `.gts` source. As a side effect, existing `{{! @glint-expect-error }}` directives covering these comparisons now report TS2578 "Unused '@ts-expect-error' directive", tempting users to delete suppressions that still guard real type errors.

1.8.5 behaves correctly. Bisected to 1.8.6; the cause is #1179 (control-flow narrowing through operator special forms).

## Reproduction

```jsonc
// package.json
{
  "devDependencies": {
    "@glimmer/component": "^2.0.0",
    "@glint/ember-tsc": "1.8.6",
    "@glint/template": "1.7.8",
    "ember-source": "7.1.0",
    "typescript": "6.0.3"
  }
}
```

```jsonc
// tsconfig.json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "bundler",
    "strict": true,
    "noEmit": true,
    "skipLibCheck": true,
    "types": ["ember-source/types", "@glint/ember-tsc/types"]
  },
  "include": ["src"]
}
```

```gts
// src/demo.gts
import Component from '@glimmer/component';

export default class Demo extends Component {
  kind: 'a' | 'b' = 'a';

  <template>
    {{#if (eq this.kind "z")}}one{{/if}}

    {{! @glint-expect-error this.kind can never be "z" }}
    {{#if (eq this.kind "z")}}two{{/if}}
  </template>
}
```

Run `ember-tsc --noEmit`.

**With 1.8.5 (expected):**

```
src/demo.gts(7,15): error TS2367: This comparison appears to be unintentional because the types '"a" | "b"' and '"z"' have no overlap.
```

(1 error on the unsuppressed comparison; the directive on the second one is honored.)

**With 1.8.6 through 1.8.10 (actual):**

```
src/demo.gts(9,5): error TS2578: Unused '@ts-expect-error' directive.
```

(The TS2367 on line 7 is gone, and the directive flips to unused.)

## Root cause

#1179 moved the keyword-consumption comma expression from around the whole operator expression into the **first operand**, so the emitted comparison changed:

```ts
// 1.8.5
(__glintDSL__.noop(__glintDSL__.Globals.eq), (__glintRef__.this.kind === "z"))
// 1.8.6+
((__glintDSL__.noop(__glintDSL__.Globals.eq), __glintRef__.this.kind) === "z")
```

TypeScript reports TS2367 on the binary expression node. In the 1.8.5 shape, that node is the inner `this.kind === "z"`, whose span starts at `this.kind` — mapped back to the template, so the diagnostic surfaces (and `@glint-expect-error` can suppress it). In the 1.8.6+ shape, the binary expression's span starts at the synthetic `((__glintDSL__.noop(...)` text, which has no mapping back to the source, so the diagnostic is silently discarded.

Verified by typechecking a transformed module's `transformedContents` directly as plain TS: TS2367 is present on every such comparison line under 1.8.6+ emission — it just never survives the mapping.

## Impact

- Real type errors (impossible comparisons) silently disappear — the checking regressed without any signal.
- Codebases that had `{{! @glint-expect-error }}` on these comparisons get a wave of TS2578 "unused directive" errors on upgrade, and deleting the directives codifies the lost coverage: if the mapping is ever fixed, all the errors come back.

## Possible fix directions

- Attach the consumption to the **right** operand instead: `(this.kind === (__glintDSL__.noop(eq), "z"))`. The expression start stays on the mapped left operand, and narrowing should be unaffected (TS narrows on unit types, not literal syntax).
- Or more generally: when a diagnostic's span starts in synthetic text but intersects mapped source ranges, map it to the intersecting range instead of dropping it. That would also rescue other diagnostics that span generated wrappers.
