### ISSUE TITLE
`<LinkTo>` doesn't require `@route` if `@query` is provided

### ISSUE THREAD

**Issue by wagenet** [typed-ember/glint#102]
Maybe this is a bad practice, but it does actually work despite glint being unhappy.

```
app/components/sortable-header.hbs:3:5 - error TS2345: Argument of type '{ query: { sortKey: string; }; }' is not assignable to parameter of type 'LinkToArgs'.
  Property 'route' is missing in type '{ query: { sortKey: string; }; }' but required in type 'LinkToArgs'.

  3     <LinkTo @query={{hash sortKey=this.sortKey}}>
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  4       <span class="sortable-header-name">
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
 13       </span>
    ~~~~~~~~~~~~~
 14     </LinkTo>
```

**Comment by wagenet** [comment]
I can't find docs that validate this, but this issue seems to support this behavior https://github.com/emberjs/ember.js/issues/17963.
