### ISSUE TITLE
glint 1.0.0-beta.2 attempts to typecheck addons not included in tsconfig

### ISSUE THREAD

**Issue by bwbuchanan** [typed-ember/glint#507]
After updating from v0.9.7 to v1.0.0-beta.2, glint reports numerous error messages from `ember-basic-dropdown`, e.g.

```
▸ yarn lint:glint
../node_modules/ember-basic-dropdown/addon/components/basic-dropdown.hbs:8:12 - error TS2339: Property 'triggerComponent' does not exist on type 'Args'.

8       (eq @triggerComponent undefined)
             ~~~~~~~~~~~~~~~~

../node_modules/ember-basic-dropdown/addon/components/basic-dropdown.hbs:10:9 - error TS2769: Unknown component name 'basic-dropdown-trigger'. If this isn't a typo, you may be missing a registry entry for this name; see the Template Registry page in the Glint documentation for more details.
  No overload matches this call.
    The last overload gave the following error.
      Argument of type 'string' is not assignable to parameter of type 'abstract new (...args: unknown[]) => InvokableInstance<(...args: [...positional: unknown[], named: unknown]) => ComponentReturn<any, any>>'.

10         'basic-dropdown-trigger'
```

I can't see any reason that `node_modules` should be in-scope for glint. It's not present in `"include"` in tsconfig.json.

My glint config:

```
"glint": {
    "checkStandaloneTemplates": false,
    "environment": ["ember-loose", "ember-template-imports"]
  }
```

I'm also not directly importing `ember-basic-dropdown` anywhere in my project. It's being pulled in as a dependency of `ember-power-select`, however, which is explicitly imported by one of my components. Removing that import resolves the errors above, but placing a `//@ts-ignore` comment above the import does not.
 
If it's not immediately obvious why `node_modules` is getting included in scope, I can attempt to put together a minimal reproduction repo.

**Comment by bwbuchanan** [comment]
Strangely, the intermediate representation for the addon's templates also does not appear in `GLINT_DEBUG` when I invoke glint with `--debug-intermediate-representation`.

**Comment by dfreeman** [comment]
This is intended and correct behavior for Glint 🙂 

Prior to the 1.0 betas, we implicitly ignored paths with `node_modules` in them, which was fairly arbitrary and diverged from TypeScript's own behavior, which is to always typecheck non-declaration files it encounters, regardless of where they're located.

In general (not specific to Glint at all), it's very strongly preferable to avoid importing source `.ts` files from code that isn't a part of the project you're actively developing. This isolates you from spurious errors, and is also a major performance boost to your typechecking, as `.d.ts` files are significantly simpler than their source counterparts and don't require the typechecker to perform any inference. That fact is the core insight behind TS's [composite projects](https://www.typescriptlang.org/docs/handbook/project-references.html) feature.

In the specific case you're reporting here, I'd guess you're hitting the issue @wagenet [fixed in `ember-power-select`](https://github.com/cibernox/ember-power-select/commit/3124da205761e98d609856a245c6751dd82a9a58) a couple weeks ago, where it was unintentionally referencing types from `basic-dropdown`'s source files instead of its declarations.

**Comment by bwbuchanan** [comment]
Thanks for the clarification!

**Comment by bendemboski** [comment]
Is there a workaround for this until that fix in `ember-power-select` is released?

**Comment by bwbuchanan** [comment]
> Is there a workaround for this until that fix in `ember-power-select` is released?

You could locally apply the patch from https://github.com/cibernox/ember-basic-dropdown/pull/687
