### ISSUE TITLE
`{{fn}}` with a generic callback no longer infers from the arg's type (regression from #1189)

### ISSUE THREAD

**Issue by BoussonKarel** [typed-ember/glint#1247]
Follow-up to #1147 / #1189. The comma-pair emit for `fn` fixed my original case, but it now rejects `{{fn}}` calls that are type-correct when the callback's type parameters depend on each other.

**Versions:** `@glint/ember-tsc` ≥ 1.8.9 (worked in ≤ 1.8.8), `@glint/template` 1.9.0, TypeScript 5.9.3

### Reproduction

```gts
import Component from '@glimmer/component';
import { fn } from '@ember/helper';

interface Person {
  name: string;
  age: number;
}

class Field<M, K extends keyof M> extends Component<{
  Args: { model: M; field: K; onChange: (value: M[K]) => void };
}> {}

export default class Form extends Component {
  person: Person = { name: 'Tomster', age: 13 };

  update = <K extends keyof Person, V extends Person[K]>(key: K, value: V) => {
    console.log(key, value);
  };

  <template>
    <Field @model={{this.person}} @field="name" @onChange={{fn this.update "name"}} />
  </template>
}
```

### Actual

```
error TS2769: No overload matches this call.
  Overload 2 of 9, '(f: (a: "name", value: string | number) => void, a: "name"): (value: ve the following error.
    Types of parameters 'value' and 'value' are incompatible.
      Type 'string | number' is not assignable to type 'string'.
```

### Expected

No error. `fn this.update "name"` gives `(value: string) => void`, which matches `@onChange: (value: Person["name"]) => void`.

### Cause

Since #1189, `{{fn f a}}` in an argument position compiles to:

```ts
onChange: (resolve(fn)(f, a), bindPositional(f, a))
```

The `resolve(fn)(…)` call on the left of the comma has no expected type. Without one, TypeScript can't infer `V extends Person[K]`, so it falls back to the union `string | number`, and the overload check
fails. Before #1189, the `fn` call sat directly in the arg slot, got `onChange`'s expecte were inferred.

The same thing happens in plain TS:

```ts
declare function fn<A, R, Args extends unknown[]>(f: (a: A, ...rest: Args) => R, a: A): (...rest: Args) => R;
declare const update: <K extends keyof Person, V extends Person[K]>(key: K, value: V) =>
declare function field<M, K extends keyof M>(args: { model: M; field: K; onChange: (v: M[K]) => void }): void;
declare const person: Person;

field({ model: person, field: 'name', onChange: fn(update, 'name') });             // ✅
field({ model: person, field: 'name', onChange: (fn(update, 'name'), 0 as any) }); // ❌ same error
```

A fix should keep the #1147 repro (`(component … onChange=(fn …))` keeping its type) and

### Workaround

Curry the callback and skip `fn`:

```ts
update = <K extends keyof Person>(key: K) => (value: Person[K]) => { … };
```

```hbs
@onChange={{this.update "name"}}
```
